//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PayRollManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Company_Salary
    {
        public string CompanyName { get; set; }
        public string EmployeeId { get; set; }
        public string AdjustmentName { get; set; }
        public Nullable<double> AdjustmentValue { get; set; }
        public string AdjustmentType { get; set; }
    }
}
