//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PayRollManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee_Info
    {
        public int CompanyId { get; set; }
        public string EmployeeId { get; set; }
        public string EmployeeName { get; set; }
        public System.DateTime DOJ { get; set; }
        public Nullable<System.DateTime> DOL { get; set; }
        public string IsAdmin { get; set; }
        public string Password { get; set; }
    }
}
