//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PayRollManager.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PayRollManagerEntities : DbContext
    {
        public PayRollManagerEntities()
            : base("name=PayRollManagerEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Attendance_Details> Attendance_Details { get; set; }
        public virtual DbSet<Company_Info> Company_Info { get; set; }
        public virtual DbSet<Employee_Info> Employee_Info { get; set; }
        public virtual DbSet<Employee_Salary> Employee_Salary { get; set; }
        public virtual DbSet<Payroll_History> Payroll_History { get; set; }
        public virtual DbSet<Personal_Details> Personal_Details { get; set; }
        public virtual DbSet<Salary_Bonus> Salary_Bonus { get; set; }
        public virtual DbSet<Salary_Increments> Salary_Increments { get; set; }
        public virtual DbSet<Session_Tokens> Session_Tokens { get; set; }
    }
}
