//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PayRollManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Salary_Slab
    {
        public int CompanyId { get; set; }
        public double FromAmount { get; set; }
        public double ToAmount { get; set; }
        public double Value { get; set; }
    }
}
