//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PayRollManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Salary_Increments
    {
        public int CompanyId { get; set; }
        public string EmployeeId { get; set; }
        public System.DateTime ApplyDate { get; set; }
        public string IncrementName { get; set; }
        public string IncrementType { get; set; }
        public double IncrementValue { get; set; }
    }
}
