//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PayRollManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Salary_Bonus
    {
        public int CompanyId { get; set; }
        public string EmployeeId { get; set; }
        public System.DateTime ApplyDate { get; set; }
        public string BonusName { get; set; }
        public string BonusType { get; set; }
        public double BonusValue { get; set; }
        public int TargetAttendance { get; set; }
        public int NoOfRepeatsLeft { get; set; }
    }
}
